name: food
description: "Đồ án thực tập tốt nghiệp - Bảo Hoàng."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  firebase_core: ^2.30.1
  schedulers: ^1.0.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400