// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJWzRJZMbh3-dh127O834TnER5XCu5djE',
    appId: '1:808266078854:web:6c1823bbdd1ae8dfbc0f07',
    messagingSenderId: '808266078854',
    projectId: 'food-app-10aee',
    authDomain: 'food-app-10aee.firebaseapp.com',
    storageBucket: 'food-app-10aee.appspot.com',
    measurementId: 'G-E69MS7EJMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5K-cu0u1MSW1BQ6syv2FSyM0Xo1VK5JQ',
    appId: '1:808266078854:android:ef91a7a340b06a95bc0f07',
    messagingSenderId: '808266078854',
    projectId: 'food-app-10aee',
    storageBucket: 'food-app-10aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArrCUiVoYT4L5HE9MGvY5-DQEC3LqM03o',
    appId: '1:808266078854:ios:731e240a68866243bc0f07',
    messagingSenderId: '808266078854',
    projectId: 'food-app-10aee',
    storageBucket: 'food-app-10aee.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArrCUiVoYT4L5HE9MGvY5-DQEC3LqM03o',
    appId: '1:808266078854:ios:731e240a68866243bc0f07',
    messagingSenderId: '808266078854',
    projectId: 'food-app-10aee',
    storageBucket: 'food-app-10aee.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJWzRJZMbh3-dh127O834TnER5XCu5djE',
    appId: '1:808266078854:web:ebae3a4f93b5cb78bc0f07',
    messagingSenderId: '808266078854',
    projectId: 'food-app-10aee',
    authDomain: 'food-app-10aee.firebaseapp.com',
    storageBucket: 'food-app-10aee.appspot.com',
    measurementId: 'G-35J0ZESVKS',
  );
}
